### ISSUE TITLE
Web socket data incorrect format

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/MicroServiceDashboard#2]
The data pushed by web sockets appears to not be mapped to the Entity but be the raw json. Comments above each method below:

Note: `this.actuatorService.getServices()` returns **Actuator**

### Controller
```java
    // Passes the Actuator object correctly
    @RequestMapping(value = {"/"}, method = RequestMethod.GET)
    public String list(Model model) {

        model.addAttribute("services", this.actuatorService.getServices());

        return "list";
    }

    // Passes the raw json not the mapped entity
    @Scheduled(fixedDelay = 1000)
    public void pushData() {
        this.messagingTemplate.convertAndSend(
                "/actuators/latest", this.actuatorService.getServices());
    }
```

**Comment by eddiejaoude** [comment]
Right, I think I know why, but not how to solve it yet.

Its due to this annotation:

```java
    @JsonProperty("mem.free")
    private Integer memoryFree = 0;
```

The external json is `mem.free`, hence the annotation, but now when it serialises, it uses that annotation too. 

Is there a way to have an annotation for deserialising and then serialising?

**Comment by simoncasey** [comment]
check this out for a custom serializer (you'll probably want section 4.)
http://www.baeldung.com/jackson-custom-serialization

and here for deserializer if you need it:
http://www.baeldung.com/jackson-deserialization

**Comment by eddiejaoude** [comment]
Solved by putting annotation on **getter/setter**...

```java
private Integer memoryFree = 0;

@JsonProperty("mem.free")
// setter

@JsonProperty("memory")
// getter
```
